version: '3'
services:
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    networks:
      - app-network

  dramatiq:
    build:
      context: .
      dockerfile: Dockerfile-dramatiq  # Change this to the actual filename
    command: ["poetry", "run", "dramatiq", "tapvalidator.tasks", "-p", "4", "-t", "4"]
    depends_on:
      - redis
    networks:
      - app-network

  tapvalidator:
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TAP_SERVICE=http://your_tap_service_url
      - MODE=your_mode_value
      - SLACK_WEBHOOK=https://your_slack_webhook_url
    command: ["poetry", "run", "python", "/app/src/tapvalidator/tap_validator.py", "--tap_service", "$TAP_SERVICE", "--mode", "$MODE", "--slack_webhook", "$SLACK_WEBHOOK"]
    depends_on:
      - dramatiq
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
